### ISSUE TITLE
[question] is this reported at artemis project?

### ISSUE THREAD

**Issue by archenroot** [CJSCommonPlatform/artemis-failure-test#4]
Hi,

I am very interested in this large messages feature, so is it that buggy still?

Have you reported to the upstream the bug?

Ladislav

**Comment by purple52** [comment]
Yes, the issue still exists in Artemis. We created this example project to reproduce and demonstrate [ARTEMIS-1022](https://issues.apache.org/jira/browse/ARTEMIS-1022). This issue is specific to interoperability between JMS and Openwire, so depending on your use case you might not be affected by it.
